In [1]:
import numpy as np

# Load Data
from tensorflow.examples.tutorials.mnist import input_data


In [2]:
emotion_label ={}
emotion_label["Neutral"] =0
emotion_label["Happy"] =1
emotion_label["Sad"] =2
emotion_label["Surprise"] =3
emotion_label["Angry"] =4
emotion_label["Disgust"] =5
emotion_label["Fear"] =6

print(emotion_label)


{'Angry': 4, 'Sad': 2, 'Neutral': 0, 'Disgust': 5, 'Surprise': 3, 'Fear': 6, 'Happy': 1}


In [3]:
def convertToOneHot(labels, num_classes):
        one_hot = np.zeros((len(labels), num_classes))

        for i in range(len(labels)):
                j =int(labels[i][0])
                one_hot[i][j] = 1
        return one_hot
        #print(one_hot)



In [8]:
array = []
train_label =[]
with open("train_images/Labels/labels.txt", "r") as f:
    data =f.readlines()
    line =data[0]
    line =line.strip()
    val =line.split()
    for values in val:
       array.append(values)
  

In [9]:
print(array)


['4', '4', '4', '5', '5', '5', '6', '6', '6', '6', '1', '1', '1', '1', '0', '0', '0', '2', '2', '2', '3', '3', '3', '4', '4', '4', '5', '5', '5', '5', '6', '6', '6', '1', '1', '1', '0', '0', '0', '2', '2', '2', '3', '3', '3', '4', '4', '4', '5', '5', '6', '6', '6', '1', '1', '1', '1', '0', '0', '0', '2', '2', '2', '2', '3', '3', '3', '4', '4', '4', '5', '5', '5', '6', '6', '6', '1', '1', '0', '0', '0', '2', '2', '2', '3', '3', '3', '4', '4', '4', '5', '5', '5', '6', '6', '6', '1', '1', '1', '0', '0', '0', '2', '2', '2', '3', '3', '3', '4', '4', '4', '5', '5', '5', '6', '6', '6', '1', '1', '1', '0', '0', '0', '2', '2', '2', '3', '3', '3', '4', '4', '4', '5', '5', '6', '6', '6', '1', '1', '1', '0', '0', '0', '2', '2', '2', '3', '3', '3']


In [10]:
train_label =[]
train_label =convertToOneHot(array,7)


In [11]:
print(train_label[:5,:])

[[ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]]


In [15]:
array = []
train_label =[]
with open("test_images/Labels/labels.txt", "r") as f:
    data =f.readlines()
    line =data[0]
    line =line.strip()
    val =line.split()
    for values in val:
       array.append(values)

In [16]:
test_label =[]


In [17]:
print(test_label[:5,:])

[[ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]]
